# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-projeto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-projeto
  template:
    metadata:
      labels:
        app: meu-projeto
    spec:
      containers:
      - name: meu-projeto-container
        # Esta linha ser√° atualizada automaticamente pelo seu CI/CD
        image: muliropetri123/hello-app:6eda1b71041d0e0ce284705ad34cdf5d598ea8b6
        ports:
        - containerPort: 80